version: '2'
services:
  netbox: &netbox
    build:
      context: .
      args:
        - BRANCH=${VERSION}
    image: ninech/netbox:${VERSION}
    depends_on:
    - postgres
    - redis
    - netbox-worker
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - EMAIL_SERVER
      - EMAIL_PORT
      - EMAIL_USERNAME
      - EMAIL_PASSWORD
      - EMAIL_TIMEOUT
      - EMAIL_FROM
      - MEDIA_ROOT
      - NAPALM_USERNAME
      - NAPALM_PASSWORD
      - NAPALM_TIMEOUT
      - MAX_PAGE_SIZE
      - REDIS_HOST
      - REDIS_PASSWORD
      - SECRET_KEY
      - SUPERUSER_NAME
      - SUPERUSER_EMAIL
      - SUPERUSER_PASSWORD
      - SUPERUSER_API_TOKEN
      - WEBHOOKS_ENABLED
    volumes:
    - netbox-nginx-config:/etc/netbox-nginx/
    - netbox-static-files:/opt/netbox/netbox/static
    - netbox-media-files:/opt/netbox/netbox/media
    - netbox-report-files:/etc/netbox/reports:ro
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    entrypoint:
    - python3
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
  nginx:
    command: nginx -c /etc/netbox-nginx/nginx.conf
    image: nginx:1.15-alpine
    depends_on:
    - netbox
    ports:
    - 8080
    volumes:
    - netbox-static-files:/opt/netbox/netbox/static:ro
    - netbox-nginx-config:/etc/netbox-nginx/:ro
  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:4-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    environment:
      - REDIS_PASSWORD
    volumes:
    - netbox-redis-data:/data
volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
  netbox-media-files:
    driver: local
  netbox-report-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
